name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 14

    - run: npm install
    - run: npm run hoist
    - run: npm run build
    
    - run: mkdir -p build

    - name: Converts @kkt/ssr Markdown to HTML
      uses: jaywcjlove/markdown-to-html-cli@main
      with:
        output: build/index.html

    - name: Generate Contributors Images
      uses: jaywcjlove/github-action-contributors@main
      with:
        filter-author: (renovate\[bot\]|renovate-bot|dependabot\[bot\])
        output: build/CONTRIBUTORS.svg
        avatarSize: 42

    - name: Create Tag
      id: create_tag
      uses: jaywcjlove/create-tag-action@v1.3.5
      with:
        package-path: ./core/package.json

    - name: get tag version
      id: tag_version
      uses: jaywcjlove/changelog-generator@v1.5.0

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        commit_message: ${{steps.tag_version.outputs.tag}} ${{ github.event.head_commit.message }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
  
    - name: Generate Changelog
      id: changelog
      uses: jaywcjlove/changelog-generator@v1.5.0
      if: steps.create_tag.outputs.successful
      with:
        filter-author: (renovate-bot|Renovate Bot)
        filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'

    - name: Create Release
      uses: ncipollo/release-action@v1
      if: steps.create_tag.outputs.successful
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: ${{ steps.create_tag.outputs.version }}
        tag: ${{ steps.create_tag.outputs.version }}
        body: |
          
          ${{ steps.changelog.outputs.compareurl }}

          ${{ steps.changelog.outputs.changelog }}

          Document @kkt/ssr @${{ steps.create_tag.outputs.version }}:

    - run: npm install @jsdevtools/npm-publish -g
    - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./core/package.json
    - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/react-ssr-enhanced/package.json
