name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    outputs:
      version: ${{ steps.create_tag.outputs.versionNumber || steps.create_tag.outputs.version || steps.create_tag.outputs.preversion }}
    steps:
    - uses: actions/checkout@master

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 14

    - run: npm install
    - run: npm run hoist
    - run: npm run build
    
    - run: mkdir -p build

    - name: Converts @kkt/ssr Markdown to HTML
      uses: jaywcjlove/markdown-to-html-cli@main
      with:
        output: build/index.html
        github-corners: https://github.com/kktjs/ssr.git

    - name: Converts create-kkt-ssr Markdown to HTML
      uses: jaywcjlove/markdown-to-html-cli@main
      with:
        output: build/create-kkt-ssr.html
        github-corners: https://github.com/kktjs/ssr/tree/master/packages/create-kkt-ssr

    - name: Generate Contributors Images
      uses: jaywcjlove/github-action-contributors@main
      with:
        filter-author: (renovate\[bot\]|renovate-bot|dependabot\[bot\])
        output: build/CONTRIBUTORS.svg
        avatarSize: 42

    - name: Create Tag
      id: create_tag
      uses: jaywcjlove/create-tag-action@v1.3.5
      with:
        package-path: ./core/package.json

    - name: get tag version
      id: tag_version
      uses: jaywcjlove/changelog-generator@v1.5.0

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        commit_message: ${{steps.tag_version.outputs.tag}} ${{ github.event.head_commit.message }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
  
    - name: Generate Changelog
      id: changelog
      uses: jaywcjlove/changelog-generator@v1.5.0
      if: steps.create_tag.outputs.successful
      with:
        filter-author: (renovate-bot|Renovate Bot)
        filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'

    - name: Create Release
      uses: ncipollo/release-action@v1
      if: steps.create_tag.outputs.successful
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: ${{ steps.create_tag.outputs.version }}
        tag: ${{ steps.create_tag.outputs.version }}
        body: |
          Documentation ${{ steps.changelog.outputs.tag }}: https://raw.githack.com/kktjs/ssr/${{ steps.changelog.outputs.gh-pages-short-hash }}/index.html  
          Comparing Changes: ${{ steps.changelog.outputs.compareurl }} 

          ${{ steps.changelog.outputs.changelog }}

    - name: 📦 @kkt/ssr publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        package: ./core/package.json

    - name: 📦 @kkt/react-ssr-enhanced publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        package: ./packages/react-ssr-enhanced/package.json

